import { getNudges } from "@/lib/db/nudge-actions";
import { NudgeList } from "@/components/nudges/nudge-list";

export const dynamic = "force-dynamic";

export default async function NudgesPage() {
  const nudges = await getNudges();
  const pendingCount = nudges.filter((n) => n.status === "PENDING").length;

  return (
    <section className="flex flex-col gap-8">
      <header>
        <p className="text-xs font-semibold uppercase tracking-[0.3em] text-slate-400">
          Nudging Agent
        </p>
        <h1 className="mt-2 text-3xl font-semibold text-slate-900">Nudges</h1>
        <p className="mt-2 max-w-2xl text-sm text-slate-500">
          Communication drafts generated by the Nudging Agent. Review each message,
          edit the copy if needed, and approve or reject before delivery.
          {pendingCount > 0 && (
            <span className="ml-2 inline-flex items-center rounded-full bg-amber-100 px-2 py-0.5 text-xs font-medium text-amber-700">
              {pendingCount} awaiting approval
            </span>
          )}
        </p>
      </header>

      <NudgeList initialNudges={nudges} />
    </section>
  );
}
