import { isDemoMode } from "@/lib/demo-mode"
import { NudgeDemoList } from "@/components/nudges/nudge-list-demo"

export const dynamic = "force-dynamic"

export default async function NudgesPage() {
  // In demo mode: show mock nudges without DB
  if (isDemoMode()) {
    return (
      <section className="flex flex-col gap-8">
        <header>
          <p className="text-[11px] font-semibold uppercase tracking-[0.3em] text-slate-600">
            Nudging Agent
          </p>
          <h1 className="mt-2 text-3xl font-semibold text-white">Nudges</h1>
          <p className="mt-1.5 max-w-2xl text-sm text-slate-400">
            Communication drafts generated by the Nudging Agent. Review each
            message, edit the copy if needed, and approve or reject before
            delivery.
          </p>
        </header>
        <NudgeDemoList />
      </section>
    )
  }

  // Live mode: use DB
  const { getNudges } = await import("@/lib/db/nudge-actions")
  const { NudgeList } = await import("@/components/nudges/nudge-list")
  const nudges = await getNudges()
  const pendingCount = nudges.filter((n) => n.status === "PENDING").length

  return (
    <section className="flex flex-col gap-8">
      <header>
        <p className="text-[11px] font-semibold uppercase tracking-[0.3em] text-slate-600">
          Nudging Agent
        </p>
        <h1 className="mt-2 text-3xl font-semibold text-white">Nudges</h1>
        <p className="mt-1.5 max-w-2xl text-sm text-slate-400">
          Communication drafts generated by the Nudging Agent. Review each
          message, edit the copy if needed, and approve or reject before
          delivery.
          {pendingCount > 0 && (
            <span className="ml-2 inline-flex items-center rounded-full bg-amber-500/10 border border-amber-500/20 px-2 py-0.5 text-xs font-medium text-amber-400">
              {pendingCount} awaiting approval
            </span>
          )}
        </p>
      </header>
      <NudgeList initialNudges={nudges} />
    </section>
  )
}
