import { isDemoMode } from "@/lib/demo-mode"
import { NudgeDemoList } from "@/components/nudges/nudge-list-demo"

export const dynamic = "force-dynamic"

export default async function NudgesPage() {
  // In demo mode: show mock nudges without DB
  if (isDemoMode()) {
    return (
      <section className="flex flex-col gap-8">
        <header>
          <p
            className="text-[10px] mb-1.5"
            style={{
              color: "#3a3a3f",
              fontFamily: "var(--font-jetbrains-mono)",
              letterSpacing: "0.15em",
            }}
          >
            // NUDGING AGENT
          </p>
          <h1
            className="text-3xl font-bold"
            style={{ fontFamily: "var(--font-syne)", color: "#f0ede8" }}
          >
            Nudges
          </h1>
          <p className="mt-1.5 max-w-2xl text-sm" style={{ color: "#6b6b70" }}>
            Communication drafts generated by the Nudging Agent. Review each
            message, edit the copy if needed, and approve or reject before
            delivery.
          </p>
        </header>
        <NudgeDemoList />
      </section>
    )
  }

  // Live mode: use DB
  const { getNudges } = await import("@/lib/db/nudge-actions")
  const { NudgeList } = await import("@/components/nudges/nudge-list")
  const nudges = await getNudges()
  const pendingCount = nudges.filter((n) => n.status === "PENDING").length

  return (
    <section className="flex flex-col gap-8">
      <header>
        <p
          className="text-[10px] mb-1.5"
          style={{
            color: "#3a3a3f",
            fontFamily: "var(--font-jetbrains-mono)",
            letterSpacing: "0.15em",
          }}
        >
          // NUDGING AGENT
        </p>
        <h1
          className="text-3xl font-bold"
          style={{ fontFamily: "var(--font-syne)", color: "#f0ede8" }}
        >
          Nudges
        </h1>
        <p className="mt-1.5 max-w-2xl text-sm" style={{ color: "#6b6b70" }}>
          Communication drafts generated by the Nudging Agent. Review each
          message, edit the copy if needed, and approve or reject before
          delivery.
          {pendingCount > 0 && (
            <span
              className="ml-2 inline-flex items-center rounded border px-2 py-0.5 text-[10px] font-medium"
              style={{
                color: "#f59e0b",
                borderColor: "#92400e",
                backgroundColor: "rgba(245,158,11,0.06)",
                fontFamily: "var(--font-jetbrains-mono)",
              }}
            >
              {pendingCount} awaiting approval
            </span>
          )}
        </p>
      </header>
      <NudgeList initialNudges={nudges} />
    </section>
  )
}
